config/routes.rb
Rails.application.routes.draw do

  resources :languages

  resources :manual_languages

  root 'languages#index'
end

app/models/language.rb
class Language < ActiveRecord::Base

  # Enable the full text search in this fields
  searchable do
    text :name, :kind, :designed_by
  end

  ##
  # It uses the default config to search
  # It assigns some fields relevance, depending on which field the match is found.
  # This can be tune and modify in several ways.
  # To read about the default parser: https://cwiki.apache.org/confluence/display/solr/The+Standard+Query+Parser
  #
  def self.lookup(text)
    languages = search do
      fulltext text do
        boost_fields name: 3.0, kind: 2.0
      end
    end
    languages.results
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController

  def index
    if params[:search].present?
      @results = Language.lookup(params[:search])
    end
  end

end

app/controllers/manual_languages_controller.rb
class ManualLanguagesController < ApplicationController

  def index
    if params[:search].present?
      languages = DataSet.instance.data_set
      filter_collection = ::Filters::FilterCollection.new(params[:search])
      @results = []

      ##
      # If the filter is produces a valid result, the result is added to the array
      # taking in account its relevance.
      # This is a O(n) algorithm. It's not the best way of doing it.
      # A better approach would be to saved an index for the data set and then just index each new entry.
      # For full-text searches, there is no rival as the inverted index data structure to boost query time performance.
      # All documents should be tokenized in simple terms and then we should build a data structure
      # where we have all documents (stored by a given id) that are matched by a term.
      # Also we could have the number of times each term matches a document,
      # useful for a more precise relevance scoring. For sake of simplicity and because we don't have new inserts here,
      # I think this algorithm accomplished the task of the test, and of course,
      # this kind of things is one of the reasons Solr or Elasticsearch are much better solutions
      #
      languages.each do |language|
        if filter_collection.valid?(language)
          relevance = filter_collection.apply!(language)
          @results[relevance] ||= []
          @results[relevance] << language
        end
      end

      # in case there are some results, it removes the nil positions,
      # flat the array and order it from the most relevant results to the less ones
      @results = @results.compact.flatten.reverse if @results.present?
    end

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/views/languages/_search_results.erb
<div class="table-responsive">
  <table id="search-results-table" class="table table-striped" cellspacing="0" width="100%">
    <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Designed by</th>
    </tr>
    </thead>
    <tbody>
      <% @results.each do |result| %>
        <tr>
          <td><%= result[:name] %></td>
          <td><%= result[:kind] %></td>
          <td><%= result[:designed_by] %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/languages/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h4>Solr full-text search</h4>
  </div>
  <div class="panel-body">
    <%= form_tag(languages_path, method: "get") do %>
      <div class="container-fluid">
        <div class='col-md-3'>
          <div class="form-group">
            <div class='input-group date' id='date-from-comp'>
              <span class="input-group-addon">
                <%= glyph(:search) %>
              </span>
              <input type='text' class="form-control" name="search" id="search" value="<%= params[:search] %>" />
            </div>
          </div>
        </div>

        <div class='col-md-3 filter-buttons-div'>
            <%= submit_tag("Search",  class: 'btn btn-primary', data: { disable_with: "Searching..." }) %>
        </div>
      </div>
    <% end %>
    <%= render 'search_results' if @results.present? %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <%= viewport_meta_tag %>
    <title><%= content_for?(:title) ? yield(:title) : "Drooms" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
      <script src="//cdnjs.cloudflare.com/ajax/libs/respond.js/1.3.0/respond.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Drooms</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li role="presentation"><%= link_to "Solr Search", languages_path %></li>
            <li role="presentation"><%= link_to "Manual Search", manual_languages_path %></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div>
    </nav>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

    </div> <!-- /container -->

  </body>
</html>

app/views/manual_languages/_search_results.erb
<div class="table-responsive">
  <table id="search-results-table" class="table table-striped" cellspacing="0" width="100%">
    <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Designed by</th>
    </tr>
    </thead>
    <tbody>
      <% @results.each do |result| %>
        <tr>
          <td><%= result['Name'] %></td>
          <td><%= result['Type'] %></td>
          <td><%= result['Designed by'] %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/manual_languages/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h4>Manual tiny search</h4>
  </div>
  <div class="panel-body">
    <%= form_tag(manual_languages_path, method: "get") do %>
      <div class="container-fluid">
        <div class='col-md-3'>
          <div class="form-group">
            <div class='input-group date' id='date-from-comp'>
              <span class="input-group-addon">
                <%= glyph(:search) %>
              </span>
              <input type='text' class="form-control" name="search" id="search" value="<%= params[:search] %>" />
            </div>
          </div>
        </div>

        <div class='col-md-3 filter-buttons-div'>
            <%= submit_tag("Search",  class: 'btn btn-primary', data: { disable_with: "Searching..." }) %>
        </div>
      </div>
    <% end %>
    <%= render 'search_results' if @results.present? %>
  </div>
</div>